name: Deploy Laravel Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Prepare environment
        run: |
          composer require --dev phpunit/phpunit "^11.0" || true

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Run Tests
        run: |
          vendor/bin/phpunit --stop-on-failure --no-coverage

      - name: Create deployment package
        run: |
          zip -r backend.zip .

      - name: Upload package to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "backend.zip"
          target: "/root/laravel_react_js_app"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/laravel_react_js_app

            # eliminar versión anterior
            rm -rf laravel-backend-app

            # crear carpeta nueva
            mkdir laravel-backend-app

            # descomprimir nueva versión
            unzip backend.zip -d laravel-backend-app
            rm backend.zip

            # colocar .env desde secret
            echo "${{ secrets.LARAVEL_ENV }}" > laravel-backend-app/.env

            # permisos
            cd laravel-backend-app
            chmod -R 775 storage bootstrap/cache

            # reiniciar contenedor php
            cd ..
            docker compose restart apiapp
